### PR TITLE
Enable annotation output for None registry

### LINKED ISSUE #409: Enable users to run publicly available models
When running the template project users are automatically redirected to sign in with their W&B. We should enable all projects to access some basic models that are publicly available (e.g. no need to register in a different platform).
@jannesgg and I talked about enabling users to select models from a model Zoo (a short list of models from Zenodo)

### PR DESCRIPTION
**Pull request by jannesgg**

### CODE REVIEW

**Comment by victor-wildlife** [comment]
I had issues with the monkey patch of the cv2.VideoWriter class when running the template project. 
image

It seems like there are no args (args just printed "[]").

I commented the CustomVideoWriter out (so just using the standard cv2.VideoWriter) and got me this far
image

I had the same issue locally and in Colab. Unfortunately, couldn't run it on Cloudina (is it down?)

**Comment by jannesgg** [comment]
@victor-wildlife I have now removed the run argument from the generate_csv_report function, so hopefully that will run for you now. I will look into the monkey patch issue as I am not able to reproduce this. 

Cloudina is unfortunately down at the moment as NAISS is doing some June maintenance that we were not aware of. We hope to have it back up asap.

**Comment by jannesgg** [comment]
@victor-wildlife Cloudina should be up again now for testing.

**Comment by victor-wildlife** [comment]
Using the template project and Spyfish after running the model selection ...
image
I get an error trying to connect to mlflow
image

**Comment by jannesgg** [comment]
> Using the template project and Spyfish after running the model selection ... image I get an error trying to connect to mlflow image

Yeah, unfortunately it seems that vendor is down and I am not sure if it will be up before next week. At the moment we should be able to get around this with mlp.registry == "wandb" .

**Pull request merged**
